# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: linguo-automation
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-pseudo-parameters
  - serverless-plugin-ifelse
  - serverless-dynamodb-local
  - serverless-offline

# package:
#   individually: true

useDotenv: true

custom:
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    packager: 'yarn'   # Packager that will be used to package your external modules
    includeModules: # enable auto-packing of external modules
      forceExclude:
        - aws-sdk

  dynamodb:
    stages:
      - kovan
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
    # Uncomment only if you already have a DynamoDB running locally
    # noStart: true

  currentStage: ${opt:stage, self:provider.stage}
  serverlessIfElse:
    - If: '"${self:custom.currentStage}" == "kovan"'
      Set:
        provider.environment.CHAIN_ID: 42
      ElseSet:
        provider.environment.CHAIN_ID: 1

  webServiceEndpoint:
    Fn::Join:
      - ''
      - - 'https://'
        - Ref: ApiGatewayRestApi
        - '.unsubscribe.'
        - Ref: AWS::Region
        - '.amazonaws.com/'
        - ${self:provider.stage}

  prune:
    automatic: true
    number: 4

provider:
  name: aws
  region: ${env:AWS_REGION,'us-east-2'}
  stage: kovan
  runtime: nodejs10.x
  apiGateway:
    shouldStartNameWithService: true
  environment:
    TASKS_TABLE_NAME: Linguo_TranslationTasks_${self:custom.currentStage}
    CHAIN_METADATA_TABLE_NAME: Linguo_ChainMetadata_${self:custom.currentStage}
    USER_SETTINGS_TABLE_NAME: Linguo_UserSettings_${self:custom.currentStage}

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: arn:aws:s3:::kleros-bots-private-keys
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource:
        Fn::Join:
          - ""
          - - arn:aws:s3:::kleros-bots-private-keys
            - "/linguo.json"
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource:
        - Fn::GetAtt: [ ChainMetadataTable, Arn ]
        - Fn::GetAtt: [ TranslationTasksTable, Arn ]
        - Fn::Join:
          - ""
          - - Fn::GetAtt: [ TranslationTasksTable, Arn ]
            - "/index/byStatus"
        - Fn::GetAtt: [ UserSettingsTable, Arn ]

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  checkNewTasks:
    handler: src/handlers/task-lifecycle/index.checkNewTasks
    timeout: 900
    events:
      - schedule:
          rate: cron(0 * * * ? *) # every hour hh:00
  checkIncompleteTasks:
    handler: src/handlers/task-lifecycle/index.checkIncompleteTasks
    timeout: 900
    events:
      - schedule:
          rate: cron(0 * * * ? *) # every hour hh:00
  checkTasksAwaitingReview:
    handler: src/handlers/task-lifecycle/index.checkTasksAwaitingReview
    timeout: 900
    events:
      - schedule:
          rate: cron(10 * * * ? *) # every hour hh:10
  checkTasksInDispute:
    handler: src/handlers/task-lifecycle/index.checkTasksInDispute
    timeout: 900
    events:
      - schedule:
          rate: cron(20 * * * ? *) # every hour hh:20
  checkResolvedTasks:
    handler: src/handlers/task-lifecycle/index.checkResolvedTasks
    timeout: 900
    events:
      - schedule:
          rate: cron(30 * * * ? *) # every hour at hh:30
  fullSync:
    timeout: 900
    handler: src/handlers/task-lifecycle/index.fullSync

  saveUserSettings:
    handler: src/handlers/user-settings/index.saveUserSettings
    events:
      - http:
          path: user/{address}/settings
          method: PUT
          cors: true
          request:
            schema:
              application/json: ${file(src/schemas/saveUserSettings.json)}
  getUserSettings:
    handler: src/handlers/user-settings/index.getUserSettings
    events:
      - http:
          path: user/{address}/settings
          method: GET
          cors: true

  unsubscribe:
    handler: src/handlers/user-settings/index.receiveUnsubscription
    events:
      - http:
          path: unsubscription
          method: GET
          cors: true

  eventsWebhook:
    handler: src/handlers/events-webhook/index.receiveEvent
    events:
      - http:
          path: event
          method: POST
          cors: true
    environment:
      UNSUBSCRIBE_ENDPOINT: https://#{ApiGatewayRestApi}.execute-api.#{AWS::Region}.amazonaws.com/${self:provider.stage}/unsubscription

# you can add CloudFormation resource templates here
resources:
  Resources:
    TranslationTasksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TASKS_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: contractAddress
            AttributeType: S
          - AttributeName: id
            AttributeType: N
          - AttributeName: status
            AttributeType: N
        KeySchema:
          - AttributeName: contractAddress
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: byStatus
            KeySchema:
              - AttributeName: status
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

    ChainMetadataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.CHAIN_METADATA_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    UserSettingsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USER_SETTINGS_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: address
            AttributeType: S
        KeySchema:
          - AttributeName: address
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

  # Outputs:
  #    NewOutput:
  #      Description: "Description for the output"
  #      Value: "Some output value"
